//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApDungDanhMucPhucVu
    {
        public int id { get; set; }
        public Nullable<int> id_danhmucmenutiecbancap1 { get; set; }
        public Nullable<int> id_danhmucmenubuffetcap1 { get; set; }
        public int id_danhmucphucvu { get; set; }
    
        public virtual DanhMucMenuBuffetCap1 DanhMucMenuBuffetCap1 { get; set; }
        public virtual DanhMucMenuTiecBanCap1 DanhMucMenuTiecBanCap1 { get; set; }
        public virtual DanhMucPhucVuMenuTiecBanVaMenuBuffet DanhMucPhucVuMenuTiecBanVaMenuBuffet { get; set; }
    }
}
