//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApDungChucNangChoQuyenTaiKhoan
    {
        public int id { get; set; }
        public int id_chucnanghethongbean { get; set; }
        public int id_quyentaikhoanbean { get; set; }
        public bool chophepthem { get; set; }
        public bool chophepsua { get; set; }
        public bool chophepxoa { get; set; }
    
        public virtual ChucNangHeThongBean ChucNangHeThongBean { get; set; }
        public virtual QuyenTaiKhoanBean QuyenTaiKhoanBean { get; set; }
    }
}
