//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoCucNoiDungTinhWebsite
    {
        public int id { get; set; }
        public string banner_trangchu { get; set; }
        public string mota_thanhphanchinh_nhahang { get; set; }
        public string mota_thanhphanchinh_vuonrau { get; set; }
        public string mota_thanhphanchinh_muasam { get; set; }
        public string mota_sanphammoi_nhahang { get; set; }
        public string mota_sanphammoi_vuonrau { get; set; }
        public string mota_sanphammoi_muasam { get; set; }
        public string mota_sanphamnoibat_nhahang { get; set; }
        public string mota_sanphamnoibat_vuonrau { get; set; }
        public string mota_sanphamnoibat_muasam { get; set; }
        public string banner_gioithieu { get; set; }
        public string tieude_gioithieu { get; set; }
        public string hinhanh1_gioithieu { get; set; }
        public string hinhanh2_gioithieu { get; set; }
        public string tieude2_gioithieu { get; set; }
        public string mota_gioithieu { get; set; }
        public string hinhanh_mota_gioithieu { get; set; }
        public string banner_nhahang { get; set; }
        public string mota_menuhangngay { get; set; }
        public string mota_menutiecban { get; set; }
        public string mota_menutiecbuffet { get; set; }
        public string banner_thucdonhangngay { get; set; }
        public string banner_tiecban { get; set; }
        public string banner_buffet { get; set; }
        public string banner_vuonrau { get; set; }
        public string banner_muasam { get; set; }
        public string banner_hinhanh { get; set; }
        public string banner_khac { get; set; }
        public string hinhanh_menuhangngay { get; set; }
        public string hinhanh_menutiecban { get; set; }
        public string hinhanh_menutiecbuffet { get; set; }
        public string mota1_gioithieu { get; set; }
        public string tieude_nhahang { get; set; }
        public string mota_nhahang { get; set; }
        public string tieude_vuonrau { get; set; }
        public string mota_vuonrau { get; set; }
        public string tieude3_gioithieu { get; set; }
        public string mota3_gioithieu { get; set; }
        public string hinhanh3_gioithieu { get; set; }
        public string hinhanh4_gioithieu { get; set; }
        public string hinhanh_menu_trangchu { get; set; }
        public string video_trangchu { get; set; }
    }
}
