//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CacBuocQuyTrinhTrongCay
    {
        public int id { get; set; }
        public int id_quytrinhtrongcay { get; set; }
        public int sobuoc { get; set; }
        public string motabuoc { get; set; }
        public string hinhanh { get; set; }
        public System.DateTime ngaytao { get; set; }
        public System.DateTime ngaysuadoi { get; set; }
    
        public virtual QuyTrinhTrongCay QuyTrinhTrongCay { get; set; }
    }
}
