//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChinhSachBean
    {
        public int id { get; set; }
        public string tenchinhsach { get; set; }
        public string noidung { get; set; }
        public int sothutu { get; set; }
        public bool hienthi { get; set; }
    }
}
