//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHangVuonRauMuaSamVaMenuHangNgay
    {
        public int id { get; set; }
        public int id_donhangvuonraumuasamvamenuhangngay { get; set; }
        public Nullable<int> id_sanphammuasam { get; set; }
        public Nullable<int> id_sanphamthucdonhangngay { get; set; }
        public string hinhanh { get; set; }
        public string video { get; set; }
        public string tensanpham { get; set; }
        public decimal gia { get; set; }
        public int soluong { get; set; }
        public string ghichu { get; set; }
    
        public virtual DonHangVuonRauMuaSamVaMenuHangNgay DonHangVuonRauMuaSamVaMenuHangNgay { get; set; }
        public virtual SanPhamMuaSam SanPhamMuaSam { get; set; }
        public virtual SanPhamThucDonHangNgay SanPhamThucDonHangNgay { get; set; }
    }
}
