//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucPhucVuMenuTiecBanVaMenuBuffet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucPhucVuMenuTiecBanVaMenuBuffet()
        {
            this.ChiTietDonHangDanhMucPhucVuMenuBuffet = new HashSet<ChiTietDonHangDanhMucPhucVuMenuBuffet>();
            this.ChiTietDonHangDanhMucPhucVuMenuTiecBan = new HashSet<ChiTietDonHangDanhMucPhucVuMenuTiecBan>();
        }
    
        public int id { get; set; }
        public int sothutu { get; set; }
        public string tendanhmuc { get; set; }
        public decimal gia { get; set; }
        public bool giatheosoban { get; set; }
        public System.DateTime ngaytao { get; set; }
        public System.DateTime ngaysuadoi { get; set; }
        public bool hienthi { get; set; }
        public bool apdungmenutiecban { get; set; }
        public bool apdungmenubuffet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangDanhMucPhucVuMenuBuffet> ChiTietDonHangDanhMucPhucVuMenuBuffet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangDanhMucPhucVuMenuTiecBan> ChiTietDonHangDanhMucPhucVuMenuTiecBan { get; set; }
    }
}
