//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucPhucVuMenuTiecBanCap1
    {
        public int id { get; set; }
        public int id_danhmucmenutiecbancap1 { get; set; }
        public int sothutu { get; set; }
        public string tendanhmuc { get; set; }
        public System.DateTime ngaytao { get; set; }
        public System.DateTime ngaysuadoi { get; set; }
        public bool hienthi { get; set; }
    
        public virtual DanhMucMenuTiecBanCap1 DanhMucMenuTiecBanCap1 { get; set; }
    }
}
