//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucMenuTiecBanCap1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucMenuTiecBanCap1()
        {
            this.DanhMucPhucVuMenuTiecBanCap1 = new HashSet<DanhMucPhucVuMenuTiecBanCap1>();
            this.SanPhamMenuTiecBan = new HashSet<SanPhamMenuTiecBan>();
        }
    
        public int id { get; set; }
        public int sothutu { get; set; }
        public string tendanhmuc { get; set; }
        public System.DateTime ngaytao { get; set; }
        public System.DateTime ngaysuadoi { get; set; }
        public bool hienthi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMucPhucVuMenuTiecBanCap1> DanhMucPhucVuMenuTiecBanCap1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamMenuTiecBan> SanPhamMenuTiecBan { get; set; }
    }
}
