//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangDanhMucPhucVu
    {
        public int id { get; set; }
        public int id_donhangmenutiecban { get; set; }
        public int id_danhmucphucvu { get; set; }
        public string tendanhmuc { get; set; }
        public decimal gia { get; set; }
        public bool giatheosoban { get; set; }
        public System.DateTime ngaytao { get; set; }
        public System.DateTime ngaysuadoi { get; set; }
        public bool apdungmenutiecban { get; set; }
        public bool apdungmenubuffet { get; set; }
    
        public virtual DanhMucPhucVuMenuTiecBanVaMenuBuffet DanhMucPhucVuMenuTiecBanVaMenuBuffet { get; set; }
        public virtual DonHangMenuTiecBan DonHangMenuTiecBan { get; set; }
    }
}
