//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangMenuBuffet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHangMenuBuffet()
        {
            this.DonHangDanhMucPhucVuMenuBuffet = new HashSet<DonHangDanhMucPhucVuMenuBuffet>();
            this.DonHangSanPhamMenuBuffet = new HashSet<DonHangSanPhamMenuBuffet>();
            this.LichSuDonHangMenuBuffet = new HashSet<LichSuDonHangMenuBuffet>();
            this.LichSuThanhToanDonHangMenuBuffet = new HashSet<LichSuThanhToanDonHangMenuBuffet>();
            this.TinhTrangDonHangMenuBuffet = new HashSet<TinhTrangDonHangMenuBuffet>();
        }
    
        public int id { get; set; }
        public string madonhang { get; set; }
        public decimal giamon { get; set; }
        public System.DateTime ngaytao { get; set; }
        public int soban { get; set; }
        public string hoten { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public System.DateTime ngaybatdau { get; set; }
        public string giobatdau { get; set; }
        public string ghichukhachhang { get; set; }
        public string ghichuquantrivien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangDanhMucPhucVuMenuBuffet> DonHangDanhMucPhucVuMenuBuffet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangSanPhamMenuBuffet> DonHangSanPhamMenuBuffet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuDonHangMenuBuffet> LichSuDonHangMenuBuffet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuThanhToanDonHangMenuBuffet> LichSuThanhToanDonHangMenuBuffet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinhTrangDonHangMenuBuffet> TinhTrangDonHangMenuBuffet { get; set; }
    }
}
