//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangMenuTiecBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHangMenuTiecBan()
        {
            this.DonHangDanhMucPhucVu = new HashSet<DonHangDanhMucPhucVu>();
            this.DonHangSanPhamMenuTiecBan = new HashSet<DonHangSanPhamMenuTiecBan>();
            this.LichSuDonHangMenuTiecBan = new HashSet<LichSuDonHangMenuTiecBan>();
            this.LichSuThanhToanDonHangMenuTiecBan = new HashSet<LichSuThanhToanDonHangMenuTiecBan>();
        }
    
        public int id { get; set; }
        public System.DateTime ngaytao { get; set; }
        public string trangthai { get; set; }
        public int soban { get; set; }
        public string hoten { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public System.DateTime ngaybatdau { get; set; }
        public string giobatdau { get; set; }
        public string ghichukhachhang { get; set; }
        public string ghichuquantrivien { get; set; }
        public string madonhang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangDanhMucPhucVu> DonHangDanhMucPhucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangSanPhamMenuTiecBan> DonHangSanPhamMenuTiecBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuDonHangMenuTiecBan> LichSuDonHangMenuTiecBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuThanhToanDonHangMenuTiecBan> LichSuThanhToanDonHangMenuTiecBan { get; set; }
    }
}
