//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHangVuonRauBean
    {
        public int id { get; set; }
        public int id_sanpham { get; set; }
        public int id_taikhoankhachhang { get; set; }
        public int soluong { get; set; }
        public System.DateTime addDate { get; set; }
    
        public virtual SanPhamRauNhaTrong SanPhamRauNhaTrong { get; set; }
        public virtual TaiKhoanKhachHang TaiKhoanKhachHang { get; set; }
    }
}
