//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int id { get; set; }
        public int id_taikhoankhachhang { get; set; }
        public Nullable<int> id_sanphamraunhatrong { get; set; }
        public Nullable<int> id_sanphamthucdonhangngay { get; set; }
        public Nullable<int> id_sanphammuasam { get; set; }
        public int soluong { get; set; }
    
        public virtual SanPhamMuaSam SanPhamMuaSam { get; set; }
        public virtual SanPhamRauNhaTrong SanPhamRauNhaTrong { get; set; }
        public virtual SanPhamThucDonHangNgay SanPhamThucDonHangNgay { get; set; }
        public virtual TaiKhoanKhachHang TaiKhoanKhachHang { get; set; }
    }
}
