//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHeDatBan
    {
        public int id { get; set; }
        public System.DateTime ngaytao { get; set; }
        public int soban { get; set; }
        public string hoten { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public System.DateTime ngaybatdau { get; set; }
        public string giobatdau { get; set; }
        public string ghichukhachhang { get; set; }
        public string ghichuquantrivien { get; set; }
        public Nullable<int> id_donhangmenutiecban { get; set; }
        public Nullable<int> id_donhangmenubuffet { get; set; }
        public string trangthai { get; set; }
    
        public virtual DonHangMenuBuffet DonHangMenuBuffet { get; set; }
        public virtual DonHangMenuTiecBan DonHangMenuTiecBan { get; set; }
    }
}
