//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MangXaHoi
    {
        public int id { get; set; }
        public string logo { get; set; }
        public string tenmangxahoi { get; set; }
        public string lienketmangxahoi { get; set; }
        public bool hienthi { get; set; }
        public int id_taikhoanbean { get; set; }
        public System.DateTime ngaytao { get; set; }
        public System.DateTime ngaysuadoi { get; set; }
    
        public virtual TaiKhoanBean TaiKhoanBean { get; set; }
    }
}
