//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeanfamilyEntities : DbContext
    {
        public BeanfamilyEntities()
            : base("name=BeanfamilyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApDungChucNangChoQuyenTaiKhoan> ApDungChucNangChoQuyenTaiKhoan { get; set; }
        public virtual DbSet<CacBuocQuyTrinhTrongCay> CacBuocQuyTrinhTrongCay { get; set; }
        public virtual DbSet<ChiTietDonHangMuaSamVaMenuHangNgay> ChiTietDonHangMuaSamVaMenuHangNgay { get; set; }
        public virtual DbSet<ChucNangHeThongBean> ChucNangHeThongBean { get; set; }
        public virtual DbSet<DanhMucMenuBuffetCap1> DanhMucMenuBuffetCap1 { get; set; }
        public virtual DbSet<DanhMucMenuTiecBanCap1> DanhMucMenuTiecBanCap1 { get; set; }
        public virtual DbSet<DanhMucPhucVuMenuBuffetCap1> DanhMucPhucVuMenuBuffetCap1 { get; set; }
        public virtual DbSet<DanhMucPhucVuMenuTiecBanCap1> DanhMucPhucVuMenuTiecBanCap1 { get; set; }
        public virtual DbSet<DanhMucSanPhamMuaSamCap1> DanhMucSanPhamMuaSamCap1 { get; set; }
        public virtual DbSet<DanhMucSanPhamRauNhaTrongCap1> DanhMucSanPhamRauNhaTrongCap1 { get; set; }
        public virtual DbSet<DanhMucThucDocHangNgayCap1> DanhMucThucDocHangNgayCap1 { get; set; }
        public virtual DbSet<DonHangMuaSamVaMenuHangNgay> DonHangMuaSamVaMenuHangNgay { get; set; }
        public virtual DbSet<GioHang> GioHang { get; set; }
        public virtual DbSet<LichSuSuaDoiSanPhamMenuBuffet> LichSuSuaDoiSanPhamMenuBuffet { get; set; }
        public virtual DbSet<LichSuSuaDoiSanPhamMenuTiecBan> LichSuSuaDoiSanPhamMenuTiecBan { get; set; }
        public virtual DbSet<LichSuSuaDoiSanPhamMuaSam> LichSuSuaDoiSanPhamMuaSam { get; set; }
        public virtual DbSet<LichSuSuaDoiSanPhamRauNhaTrong> LichSuSuaDoiSanPhamRauNhaTrong { get; set; }
        public virtual DbSet<LichSuSuaDoiSanPhamThucDonHangNgay> LichSuSuaDoiSanPhamThucDonHangNgay { get; set; }
        public virtual DbSet<NoiDungSEO> NoiDungSEO { get; set; }
        public virtual DbSet<QuyenTaiKhoanBean> QuyenTaiKhoanBean { get; set; }
        public virtual DbSet<QuyTrinhTrongCay> QuyTrinhTrongCay { get; set; }
        public virtual DbSet<SanPhamMenuBuffet> SanPhamMenuBuffet { get; set; }
        public virtual DbSet<SanPhamMenuTiecBan> SanPhamMenuTiecBan { get; set; }
        public virtual DbSet<SanPhamMuaSam> SanPhamMuaSam { get; set; }
        public virtual DbSet<SanPhamRauNhaTrong> SanPhamRauNhaTrong { get; set; }
        public virtual DbSet<SanPhamThucDonHangNgay> SanPhamThucDonHangNgay { get; set; }
        public virtual DbSet<TaiKhoanBean> TaiKhoanBean { get; set; }
        public virtual DbSet<TaiKhoanKhachHang> TaiKhoanKhachHang { get; set; }
        public virtual DbSet<TinhTrangDonHangMuaSamVaMenuHangNgay> TinhTrangDonHangMuaSamVaMenuHangNgay { get; set; }
        public virtual DbSet<ThongTinChung> ThongTinChung { get; set; }
        public virtual DbSet<MangXaHoi> MangXaHoi { get; set; }
    }
}
