//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeanfamilyEntities : DbContext
    {
        public BeanfamilyEntities()
            : base("name=BeanfamilyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApDungChucNangChoQuyenTaiKhoan> ApDungChucNangChoQuyenTaiKhoan { get; set; }
        public virtual DbSet<CacBuocQuyTrinhTrongCay> CacBuocQuyTrinhTrongCay { get; set; }
        public virtual DbSet<ChiTietDonHangDanhMucPhucVuMenuBuffet> ChiTietDonHangDanhMucPhucVuMenuBuffet { get; set; }
        public virtual DbSet<ChiTietDonHangDanhMucPhucVuMenuTiecBan> ChiTietDonHangDanhMucPhucVuMenuTiecBan { get; set; }
        public virtual DbSet<ChiTietDonHangSanPhamMenuBuffet> ChiTietDonHangSanPhamMenuBuffet { get; set; }
        public virtual DbSet<ChiTietDonHangSanPhamMenuTiecBan> ChiTietDonHangSanPhamMenuTiecBan { get; set; }
        public virtual DbSet<ChiTietDonHangSanPhamMuaSam> ChiTietDonHangSanPhamMuaSam { get; set; }
        public virtual DbSet<ChiTietDonHangSanPhamRauNhaTrong> ChiTietDonHangSanPhamRauNhaTrong { get; set; }
        public virtual DbSet<ChiTietDonHangSanPhamThucDonHangNgay> ChiTietDonHangSanPhamThucDonHangNgay { get; set; }
        public virtual DbSet<ChucNangHeThongBean> ChucNangHeThongBean { get; set; }
        public virtual DbSet<DanhMucMenuBuffetCap1> DanhMucMenuBuffetCap1 { get; set; }
        public virtual DbSet<DanhMucMenuTiecBanCap1> DanhMucMenuTiecBanCap1 { get; set; }
        public virtual DbSet<DanhMucPhucVuMenuTiecBanVaMenuBuffet> DanhMucPhucVuMenuTiecBanVaMenuBuffet { get; set; }
        public virtual DbSet<DanhMucSanPhamMuaSamCap1> DanhMucSanPhamMuaSamCap1 { get; set; }
        public virtual DbSet<DanhMucSanPhamRauNhaTrongCap1> DanhMucSanPhamRauNhaTrongCap1 { get; set; }
        public virtual DbSet<DanhMucThucDocHangNgayCap1> DanhMucThucDocHangNgayCap1 { get; set; }
        public virtual DbSet<DonHangMenuBuffet> DonHangMenuBuffet { get; set; }
        public virtual DbSet<DonHangMenuTiecBan> DonHangMenuTiecBan { get; set; }
        public virtual DbSet<DonHangVuonRauMuaSamVaMenuHangNgay> DonHangVuonRauMuaSamVaMenuHangNgay { get; set; }
        public virtual DbSet<GioHangMuaSam> GioHangMuaSam { get; set; }
        public virtual DbSet<GioHangThucDonHangNgay> GioHangThucDonHangNgay { get; set; }
        public virtual DbSet<GioHangVuonRauBean> GioHangVuonRauBean { get; set; }
        public virtual DbSet<HinhAnhBean> HinhAnhBean { get; set; }
        public virtual DbSet<LichSuThanhToanDonHangTongHop> LichSuThanhToanDonHangTongHop { get; set; }
        public virtual DbSet<NoiDungSEO> NoiDungSEO { get; set; }
        public virtual DbSet<QuyenTaiKhoanBean> QuyenTaiKhoanBean { get; set; }
        public virtual DbSet<QuyTrinhTrongCay> QuyTrinhTrongCay { get; set; }
        public virtual DbSet<SanPhamMenuBuffet> SanPhamMenuBuffet { get; set; }
        public virtual DbSet<SanPhamMenuTiecBan> SanPhamMenuTiecBan { get; set; }
        public virtual DbSet<SanPhamMuaSam> SanPhamMuaSam { get; set; }
        public virtual DbSet<SanPhamRauNhaTrong> SanPhamRauNhaTrong { get; set; }
        public virtual DbSet<SanPhamThucDonHangNgay> SanPhamThucDonHangNgay { get; set; }
        public virtual DbSet<TaiKhoanBean> TaiKhoanBean { get; set; }
        public virtual DbSet<TaiKhoanKhachHang> TaiKhoanKhachHang { get; set; }
        public virtual DbSet<TinhTrangDonHangMenuBuffet> TinhTrangDonHangMenuBuffet { get; set; }
        public virtual DbSet<TinhTrangDonHangMenuTiecBan> TinhTrangDonHangMenuTiecBan { get; set; }
        public virtual DbSet<TinhTrangDonHangVuonRauMuaSamVaMenuHangNgay> TinhTrangDonHangVuonRauMuaSamVaMenuHangNgay { get; set; }
        public virtual DbSet<TonKhoSanPhamMuaSam> TonKhoSanPhamMuaSam { get; set; }
        public virtual DbSet<ThongTinCauHinh> ThongTinCauHinh { get; set; }
    }
}
