//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyTrinhTrongCay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuyTrinhTrongCay()
        {
            this.CacBuocQuyTrinhTrongCay = new HashSet<CacBuocQuyTrinhTrongCay>();
            this.SanPhamRauNhaTrong = new HashSet<SanPhamRauNhaTrong>();
        }
    
        public int id { get; set; }
        public string tenquytrinhtrongcay { get; set; }
        public string video { get; set; }
        public System.DateTime ngaytao { get; set; }
        public System.DateTime ngaysuadoi { get; set; }
        public decimal luotxem { get; set; }
        public bool hienthi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CacBuocQuyTrinhTrongCay> CacBuocQuyTrinhTrongCay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamRauNhaTrong> SanPhamRauNhaTrong { get; set; }
    }
}
