//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamRauNhaTrong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPhamRauNhaTrong()
        {
            this.ChiTietDonHangSanPhamRauNhaTrong = new HashSet<ChiTietDonHangSanPhamRauNhaTrong>();
            this.GioHangVuonRauBean = new HashSet<GioHangVuonRauBean>();
        }
    
        public int id { get; set; }
        public int id_danhmucsanphamraunhatrongcap1 { get; set; }
        public Nullable<int> id_quytrinhtrongcay { get; set; }
        public string hinhanh { get; set; }
        public string video { get; set; }
        public string tensanpham { get; set; }
        public string donvi { get; set; }
        public int giatritrendonvi { get; set; }
        public decimal gia { get; set; }
        public string mota { get; set; }
        public decimal luotxem { get; set; }
        public bool hienthi { get; set; }
        public bool daxoa { get; set; }
        public bool thamkhao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangSanPhamRauNhaTrong> ChiTietDonHangSanPhamRauNhaTrong { get; set; }
        public virtual DanhMucSanPhamRauNhaTrongCap1 DanhMucSanPhamRauNhaTrongCap1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHangVuonRauBean> GioHangVuonRauBean { get; set; }
        public virtual QuyTrinhTrongCay QuyTrinhTrongCay { get; set; }
    }
}
