//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamMenuTiecBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPhamMenuTiecBan()
        {
            this.ChiTietDonHangSanPhamMenuTiecBan = new HashSet<ChiTietDonHangSanPhamMenuTiecBan>();
        }
    
        public int id { get; set; }
        public int id_danhmucmenutiecbancap1 { get; set; }
        public int sothutu { get; set; }
        public string hinhanh { get; set; }
        public string tensanpham { get; set; }
        public decimal gia { get; set; }
        public bool hienthi { get; set; }
        public bool daxoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangSanPhamMenuTiecBan> ChiTietDonHangSanPhamMenuTiecBan { get; set; }
        public virtual DanhMucMenuTiecBanCap1 DanhMucMenuTiecBanCap1 { get; set; }
    }
}
