//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamMuaSam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPhamMuaSam()
        {
            this.ChiTietDonHangSanPhamMuaSam = new HashSet<ChiTietDonHangSanPhamMuaSam>();
            this.GioHangMuaSam = new HashSet<GioHangMuaSam>();
            this.TonKhoSanPhamMuaSam = new HashSet<TonKhoSanPhamMuaSam>();
        }
    
        public int id { get; set; }
        public int id_danhmucmuasamcap1 { get; set; }
        public string hinhanh { get; set; }
        public string video { get; set; }
        public string tensanpham { get; set; }
        public string mota { get; set; }
        public decimal luotxem { get; set; }
        public bool hienthi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangSanPhamMuaSam> ChiTietDonHangSanPhamMuaSam { get; set; }
        public virtual DanhMucSanPhamMuaSamCap1 DanhMucSanPhamMuaSamCap1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHangMuaSam> GioHangMuaSam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TonKhoSanPhamMuaSam> TonKhoSanPhamMuaSam { get; set; }
    }
}
