//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKienBean
    {
        public int id { get; set; }
        public string tieude { get; set; }
        public string noidung { get; set; }
        public string baiviet { get; set; }
        public string hinhanh { get; set; }
        public System.DateTime ngaygio { get; set; }
    }
}
