//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanKhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoanKhachHang()
        {
            this.DonHangVuonRauMuaSamVaMenuHangNgay = new HashSet<DonHangVuonRauMuaSamVaMenuHangNgay>();
            this.GioHangMuaSam = new HashSet<GioHangMuaSam>();
            this.GioHangThucDonHangNgay = new HashSet<GioHangThucDonHangNgay>();
            this.GioHangVuonRauBean = new HashSet<GioHangVuonRauBean>();
        }
    
        public int id { get; set; }
        public string password { get; set; }
        public string hovaten { get; set; }
        public string sodienthoai { get; set; }
        public string email { get; set; }
        public string ngaysinh { get; set; }
        public string gioitinh { get; set; }
        public string diachi { get; set; }
        public System.DateTime ngaytao { get; set; }
        public System.DateTime ngaysuadoi { get; set; }
        public string hinhdaidien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangVuonRauMuaSamVaMenuHangNgay> DonHangVuonRauMuaSamVaMenuHangNgay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHangMuaSam> GioHangMuaSam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHangThucDonHangNgay> GioHangThucDonHangNgay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHangVuonRauBean> GioHangVuonRauBean { get; set; }
    }
}
