//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanBean
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoanBean()
        {
            this.LichSuDonHangMenuTiecBan = new HashSet<LichSuDonHangMenuTiecBan>();
            this.LichSuSuaDoiSanPhamMenuBuffet = new HashSet<LichSuSuaDoiSanPhamMenuBuffet>();
            this.LichSuSuaDoiSanPhamMenuTiecBan = new HashSet<LichSuSuaDoiSanPhamMenuTiecBan>();
            this.LichSuSuaDoiSanPhamMuaSam = new HashSet<LichSuSuaDoiSanPhamMuaSam>();
            this.LichSuSuaDoiSanPhamRauNhaTrong = new HashSet<LichSuSuaDoiSanPhamRauNhaTrong>();
            this.LichSuSuaDoiSanPhamThucDonHangNgay = new HashSet<LichSuSuaDoiSanPhamThucDonHangNgay>();
            this.LichSuThanhToanDonHangMenuTiecBan = new HashSet<LichSuThanhToanDonHangMenuTiecBan>();
            this.MangXaHoi = new HashSet<MangXaHoi>();
            this.TinhTrangDonHangMuaSamVaMenuHangNgay = new HashSet<TinhTrangDonHangMuaSamVaMenuHangNgay>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string hovaten { get; set; }
        public string sodienthoai { get; set; }
        public string email { get; set; }
        public string ngaysinh { get; set; }
        public string gioitinh { get; set; }
        public string diachi { get; set; }
        public int id_quyentaikhoanbean { get; set; }
        public string chucdanh { get; set; }
        public System.DateTime ngaythamgia { get; set; }
        public System.DateTime ngaysuadoi { get; set; }
        public bool khoataikhoan { get; set; }
        public int solansaimatkhautoida { get; set; }
        public int solandasaimatkhau { get; set; }
        public string hinhdaidien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuDonHangMenuTiecBan> LichSuDonHangMenuTiecBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuSuaDoiSanPhamMenuBuffet> LichSuSuaDoiSanPhamMenuBuffet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuSuaDoiSanPhamMenuTiecBan> LichSuSuaDoiSanPhamMenuTiecBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuSuaDoiSanPhamMuaSam> LichSuSuaDoiSanPhamMuaSam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuSuaDoiSanPhamRauNhaTrong> LichSuSuaDoiSanPhamRauNhaTrong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuSuaDoiSanPhamThucDonHangNgay> LichSuSuaDoiSanPhamThucDonHangNgay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuThanhToanDonHangMenuTiecBan> LichSuThanhToanDonHangMenuTiecBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MangXaHoi> MangXaHoi { get; set; }
        public virtual QuyenTaiKhoanBean QuyenTaiKhoanBean { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinhTrangDonHangMuaSamVaMenuHangNgay> TinhTrangDonHangMuaSamVaMenuHangNgay { get; set; }
    }
}
