//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinChung
    {
        public int id { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public string hotline { get; set; }
        public string zalo { get; set; }
        public string website { get; set; }
        public string coppyright { get; set; }
        public string fanpage { get; set; }
        public string toadogooglemap { get; set; }
        public string linkchiduong { get; set; }
        public string toadogooglemapiframe { get; set; }
        public string googleanalyst { get; set; }
        public string googlewebmastertool { get; set; }
        public string headjs { get; set; }
        public string bodyjs { get; set; }
        public string tieude { get; set; }
    }
}
