//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinCauHinh
    {
        public int id { get; set; }
        public string giomocua { get; set; }
        public string ngaymocua { get; set; }
        public string diachi { get; set; }
        public string email { get; set; }
        public string sodienthoai { get; set; }
        public string facebook { get; set; }
        public string messenger { get; set; }
        public string zalo { get; set; }
        public string instagram { get; set; }
        public string tiktok { get; set; }
        public string coppyright { get; set; }
        public string linkchiduong { get; set; }
        public string toadogooglemapiframe { get; set; }
        public string googleanalyst { get; set; }
        public string googlesearchconsole { get; set; }
    }
}
