//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonKhoSanPhamMuaSam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TonKhoSanPhamMuaSam()
        {
            this.GioHangMuaSam = new HashSet<GioHangMuaSam>();
        }
    
        public int id { get; set; }
        public int id_sanphammuasam { get; set; }
        public string tenloai { get; set; }
        public int soluong { get; set; }
        public decimal gia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHangMuaSam> GioHangMuaSam { get; set; }
        public virtual SanPhamMuaSam SanPhamMuaSam { get; set; }
    }
}
