//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TonKhoSanPham
    {
        public int id { get; set; }
        public int id_sanphammuasam { get; set; }
        public string tenloai { get; set; }
        public int soluong { get; set; }
        public decimal gia { get; set; }
    
        public virtual SanPhamMuaSam SanPhamMuaSam { get; set; }
    }
}
