//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beanfamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopSanPhamNoiBat
    {
        public int id { get; set; }
        public int id_thucdon { get; set; }
        public int id_vuonrau { get; set; }
        public int id_muasam { get; set; }
        public int id_thucdon_2 { get; set; }
        public int id_vuonrau_2 { get; set; }
        public int id_muasam_2 { get; set; }
    
        public virtual SanPhamMuaSam SanPhamMuaSam { get; set; }
        public virtual SanPhamRauNhaTrong SanPhamRauNhaTrong { get; set; }
        public virtual SanPhamThucDonHangNgay SanPhamThucDonHangNgay { get; set; }
        public virtual SanPhamMuaSam SanPhamMuaSam1 { get; set; }
        public virtual SanPhamRauNhaTrong SanPhamRauNhaTrong1 { get; set; }
        public virtual SanPhamThucDonHangNgay SanPhamThucDonHangNgay1 { get; set; }
    }
}
